import { PlaceType, BudgetTier, MealType, GoaRegion } from '../generated/prisma/client.js';
import { SeedPlace } from './places.js';

export const EXTRA_ATTRACTIONS: SeedPlace[] = [
  // ═══════════════════════════════════════
  // TEMPLES (5)
  // ═══════════════════════════════════════
  {
    name: 'Mahalaxmi Temple, Panaji',
    description:
      'A revered Hindu temple in the heart of Panaji dedicated to Goddess Mahalaxmi, the deity of wealth and prosperity. The temple features traditional Goan-Hindu architecture with ornate wooden carvings and a serene courtyard. It is one of the most visited temples in the capital city, especially during Navratri.',
    latitude: 15.4989,
    longitude: 73.8278,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'temple',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 45,
    bestTimeStart: '06:00',
    bestTimeEnd: '20:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['spiritual', 'heritage', 'architecture', 'peaceful', 'cultural'],
    rating: 4.4,
    reviewCount: 3200,
  },
  {
    name: 'Mahalsa Narayani Temple, Mardol',
    description:
      'One of the most important temples in Goa, dedicated to Goddess Mahalsa — a Goan form of the deity Mohini. Located in Mardol village in Ponda taluka, the temple is known for its magnificent deepstambha (lamp tower) and intricately carved silver doorway. The temple complex also includes a large sacred tank.',
    latitude: 15.3975,
    longitude: 74.0023,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'temple',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 60,
    bestTimeStart: '06:00',
    bestTimeEnd: '21:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['spiritual', 'heritage', 'architecture', 'cultural', 'historic'],
    rating: 4.5,
    reviewCount: 2800,
  },
  {
    name: 'Saptakoteshwar Temple',
    description:
      'An ancient Shiva temple situated on the picturesque Divar Island in the Mandovi river, dating back to the 12th century. Originally built by the Kadamba dynasty, the temple was destroyed during Portuguese rule and later rebuilt. The temple offers panoramic views of the surrounding river and lush green landscape.',
    latitude: 15.5145,
    longitude: 73.8815,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'temple',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 60,
    bestTimeStart: '06:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['spiritual', 'heritage', 'historic', 'island', 'scenic', 'offbeat'],
    rating: 4.3,
    reviewCount: 1450,
  },
  {
    name: 'Brahma Temple, Carambolim',
    description:
      'A rare temple dedicated to Lord Brahma, the creator god in Hindu mythology, located near Carambolim village in Old Goa. Temples dedicated to Brahma are extremely uncommon across India, making this a unique religious site. The temple is small but holds great spiritual significance and is surrounded by lush paddy fields.',
    latitude: 15.4823,
    longitude: 73.9165,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'temple',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 30,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['spiritual', 'offbeat', 'heritage', 'unique', 'peaceful'],
    rating: 4.0,
    reviewCount: 680,
  },
  {
    name: 'Ramnathi Temple',
    description:
      'A prominent Hindu temple dedicated to Lord Ramnath (a form of Shiva), located in Ramnathim village in Ponda taluka. The temple was relocated here during the Portuguese Inquisition and features beautiful Goan temple architecture with a distinctive lamp tower. It is one of the most venerated temples in Goa.',
    latitude: 15.3720,
    longitude: 74.0088,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'temple',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 45,
    bestTimeStart: '06:00',
    bestTimeEnd: '20:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['spiritual', 'heritage', 'architecture', 'cultural', 'peaceful'],
    rating: 4.4,
    reviewCount: 1950,
  },

  // ═══════════════════════════════════════
  // CHURCHES (3)
  // ═══════════════════════════════════════
  {
    name: 'Church of Our Lady of Immaculate Conception, Panaji',
    description:
      'An iconic whitewashed church perched atop a hill in the centre of Panaji, featuring a striking double-flight stairway inspired by Bom Jesus Basilica in Rome. Built in 1541 as a chapel and later rebuilt in 1619, it served as the first port of call for Portuguese sailors arriving in Goa. The church is beautifully illuminated at night and is one of the most photographed landmarks in Goa.',
    latitude: 15.4968,
    longitude: 73.8278,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'church',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 45,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'architecture', 'iconic', 'photography', 'historic', 'landmark'],
    rating: 4.6,
    reviewCount: 8900,
  },
  {
    name: 'Chapel of St. Catherine',
    description:
      'A small but historically significant chapel in Old Goa, built by Afonso de Albuquerque in 1510 to commemorate his victory over the Adil Shah. It is considered the first church built by the Portuguese in Goa and was later elevated to cathedral status by Pope Paul III. The modest laterite structure stands as a quiet witness to the beginnings of Portuguese rule in India.',
    latitude: 15.5012,
    longitude: 73.9115,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'church',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 30,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'historic', 'architecture', 'quiet', 'offbeat'],
    rating: 4.1,
    reviewCount: 1200,
  },
  {
    name: 'Church of St. Cajetan',
    description:
      'A stunning 17th-century church in Old Goa modelled after St. Peter\'s Basilica in Rome, built by Italian friars of the Theatine order. The church features a Greek cross floor plan, a grand dome, and Corinthian-style interiors that are among the finest examples of Baroque architecture in India. It is a UNESCO World Heritage Site and one of the best-preserved churches in Old Goa.',
    latitude: 15.5022,
    longitude: 73.9122,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'church',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'architecture', 'UNESCO', 'iconic', 'historic', 'baroque'],
    rating: 4.5,
    reviewCount: 4600,
  },

  // ═══════════════════════════════════════
  // BEACHES (7)
  // ═══════════════════════════════════════
  {
    name: 'Bogmalo Beach',
    description:
      'A quiet, crescent-shaped beach near Dabolim airport, popular with locals and military personnel from the nearby naval base. The sheltered cove offers calm waters ideal for swimming and is also a starting point for boat trips to Grande Island. The beach has a few laid-back shacks serving fresh seafood.',
    latitude: 15.3804,
    longitude: 73.8370,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'SOUTH' as GoaRegion,
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'quiet', 'swimming', 'family', 'offbeat'],
    rating: 4.1,
    reviewCount: 2300,
  },
  {
    name: 'Velsao Beach',
    description:
      'One of the most pristine and deserted beaches in South Goa, stretching between Bogmalo and Cansaulim. The long, unspoilt stretch of golden sand is backed by coconut palms and is ideal for solitary walks and relaxation. It remains largely untouched by commercial tourism, offering a tranquil escape.',
    latitude: 15.3676,
    longitude: 73.8604,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'SOUTH' as GoaRegion,
    estimatedDurationMinutes: 90,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'quiet', 'pristine', 'offbeat', 'peaceful', 'romantic'],
    rating: 4.2,
    reviewCount: 890,
  },
  {
    name: 'Cavelossim Beach',
    description:
      'A serene and well-maintained beach in South Goa, flanked by the Sal River on one side and the Arabian Sea on the other. Known for its distinctive black lava rocks jutting out of the white sand, the beach is popular with upscale tourists and has several luxury resorts nearby. Dolphin-watching boat rides depart from the southern end.',
    latitude: 15.1710,
    longitude: 73.9418,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'SOUTH' as GoaRegion,
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'luxury', 'dolphins', 'family', 'romantic', 'relaxing'],
    rating: 4.4,
    reviewCount: 3800,
  },
  {
    name: 'Betalbatim Beach',
    description:
      'A hidden gem in South Goa, often called the "Sunset Beach" for its spectacular west-facing sunsets. The quiet stretch of sand is dotted with a few excellent beach shacks and is one of the best spots to see dolphins close to shore. The beach connects to Colva Beach but is far less crowded.',
    latitude: 15.2895,
    longitude: 73.9175,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'SOUTH' as GoaRegion,
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'quiet', 'sunset', 'dolphins', 'offbeat', 'romantic'],
    rating: 4.3,
    reviewCount: 2100,
  },
  {
    name: 'Bambolim Beach',
    description:
      'A small, peaceful beach near Panaji and the Goa University campus, popular among locals for evening walks and jogging. The calm waters and lack of commercial activity make it a serene getaway close to the state capital. The beach offers views of the Zuari River estuary meeting the sea.',
    latitude: 15.4541,
    longitude: 73.8536,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 60,
    bestTimeStart: '06:30',
    bestTimeEnd: '18:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'quiet', 'local', 'peaceful', 'jogging'],
    rating: 3.9,
    reviewCount: 1050,
  },
  {
    name: 'Ashwem Beach',
    description:
      'A laid-back beach in North Goa, situated between Morjim and Mandrem, known for its wide sandy stretch and bohemian vibe. The beach features unique rock formations and is home to some of Goa\'s most stylish beach restaurants and boutique stays. It attracts a mix of long-stay travelers, yoga enthusiasts, and creative types.',
    latitude: 15.6442,
    longitude: 73.7290,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'NORTH' as GoaRegion,
    estimatedDurationMinutes: 150,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'bohemian', 'yoga', 'relaxing', 'trendy', 'offbeat'],
    rating: 4.4,
    reviewCount: 3400,
  },
  {
    name: 'Ozran Beach (Little Vagator)',
    description:
      'A small, picturesque cove nestled below the cliffs south of Vagator, often referred to as Little Vagator or Ozran Beach. Accessible via a steep path through the rocks, the beach is framed by dramatic red laterite cliffs and features the famous Shiva face rock carving. It remains a favourite among backpackers and psytrance culture enthusiasts.',
    latitude: 15.5948,
    longitude: 73.7345,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'beach',
    region: 'NORTH' as GoaRegion,
    estimatedDurationMinutes: 120,
    bestTimeStart: '08:00',
    bestTimeEnd: '18:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['scenic', 'cliffs', 'photography', 'backpacker', 'offbeat', 'cove'],
    rating: 4.5,
    reviewCount: 4200,
  },

  // ═══════════════════════════════════════
  // FORTS (2)
  // ═══════════════════════════════════════
  {
    name: 'Corjuem Fort',
    description:
      'A small but well-preserved Portuguese fort on Corjuem Island, built in 1705 to defend the eastern frontier of Portuguese Goa against Maratha invasions. The fort features a distinctive square plan with a single circular turret and offers quiet views of the surrounding agricultural land. It is one of the lesser-known forts in Goa and ideal for history buffs seeking offbeat destinations.',
    latitude: 15.5262,
    longitude: 73.9010,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'fort',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'historic', 'offbeat', 'architecture', 'quiet', 'photography'],
    rating: 3.9,
    reviewCount: 620,
  },
  {
    name: 'Terekhol Fort (Tiracol)',
    description:
      'A historic Portuguese fort perched on a cliff overlooking the Terekhol River and the Arabian Sea, at the northernmost tip of Goa. Built in the 17th century, the fort contains a small chapel dedicated to St. Anthony and has been converted into a heritage boutique hotel. The ramparts offer breathtaking panoramic views of Querim Beach and the Konkan coastline.',
    latitude: 15.7216,
    longitude: 73.6913,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'fort',
    region: 'NORTH' as GoaRegion,
    estimatedDurationMinutes: 60,
    bestTimeStart: '08:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'historic', 'scenic', 'photography', 'viewpoint', 'offbeat'],
    rating: 4.2,
    reviewCount: 1800,
  },

  // ═══════════════════════════════════════
  // NATURE & VIEWPOINTS (4)
  // ═══════════════════════════════════════
  {
    name: 'Salaulim Dam',
    description:
      'The largest dam in Goa, built across the Salaulim River in Sanguem taluka, surrounded by lush green hills of the Western Ghats. The dam has a well-maintained garden with a musical fountain and is a popular weekend picnic spot for families. The reservoir and surrounding landscape are especially stunning during and after the monsoon season.',
    latitude: 15.2065,
    longitude: 74.0935,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'nature',
    region: 'SOUTH' as GoaRegion,
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 20,
    mealType: 'NONE' as MealType,
    tags: ['nature', 'scenic', 'family', 'picnic', 'photography', 'monsoon'],
    rating: 4.1,
    reviewCount: 2500,
  },
  {
    name: 'Dr. Salim Ali Bird Sanctuary, Chorao Island',
    description:
      'A pristine mangrove habitat on Chorao Island in the Mandovi River, named after the renowned Indian ornithologist Dr. Salim Ali. The sanctuary spans 1.8 sq km and is home to a wide variety of bird species including kingfishers, eagles, cormorants, and migratory birds during winter. Visitors explore the sanctuary via guided boat rides through the winding mangrove creeks.',
    latitude: 15.5120,
    longitude: 73.8670,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'nature',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 120,
    bestTimeStart: '06:30',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 100,
    mealType: 'NONE' as MealType,
    tags: ['nature', 'birdwatching', 'mangrove', 'boat', 'wildlife', 'eco-tourism', 'offbeat'],
    rating: 4.2,
    reviewCount: 1900,
  },
  {
    name: 'Campal Gardens',
    description:
      'A charming urban park in Panaji along the banks of the Mandovi River, featuring tree-lined walkways, manicured lawns, and an open amphitheatre. The gardens serve as a cultural hub, frequently hosting art exhibitions, music festivals, and the annual International Film Festival of India (IFFI). It is a peaceful retreat within the bustling state capital.',
    latitude: 15.4966,
    longitude: 73.8195,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'nature',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 45,
    bestTimeStart: '06:00',
    bestTimeEnd: '20:00',
    isOpenAtNight: true,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 0,
    mealType: 'NONE' as MealType,
    tags: ['nature', 'park', 'family', 'cultural', 'relaxing', 'urban'],
    rating: 4.0,
    reviewCount: 1600,
  },
  {
    name: 'Bondla Wildlife Sanctuary',
    description:
      'The smallest but most accessible wildlife sanctuary in Goa, spread across 8 sq km of moist deciduous forest in the foothills of the Western Ghats. The sanctuary features a mini zoo, deer safari park, botanical garden, and nature trails frequented by sambar deer, bison, and various bird species. It is especially popular for school excursions and family day trips.',
    latitude: 15.4195,
    longitude: 74.1532,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'nature',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 150,
    bestTimeStart: '09:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 20,
    mealType: 'NONE' as MealType,
    tags: ['nature', 'wildlife', 'family', 'trekking', 'birdwatching', 'safari'],
    rating: 4.0,
    reviewCount: 2900,
  },

  // ═══════════════════════════════════════
  // MARKETS (2)
  // ═══════════════════════════════════════
  {
    name: 'Panaji Municipal Market (KTC Market)',
    description:
      'The main municipal market of Goa\'s capital city, located near the Kadamba bus terminus. The bustling market sells everything from fresh fish, vegetables, and spices to local Goan sausages (chouriço) and cashew feni. It is an authentic local experience and a fantastic place to sample the flavours and colours of everyday Goan life.',
    latitude: 15.4975,
    longitude: 73.8310,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'market',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 60,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 200,
    mealType: 'NONE' as MealType,
    tags: ['local', 'food', 'shopping', 'cultural', 'authentic', 'spices'],
    rating: 4.1,
    reviewCount: 1750,
  },
  {
    name: 'Margao Market (Municipal Market)',
    description:
      'The largest and liveliest covered market in South Goa, located in the commercial capital of Margao (Madgaon). The old Portuguese-era market building houses hundreds of stalls selling fresh produce, fish, meat, spices, textiles, and local handicrafts. The surrounding streets are lined with traditional Goan houses and colonial-era shops, making it a great area for a walking exploration.',
    latitude: 15.2832,
    longitude: 73.9565,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'market',
    region: 'SOUTH' as GoaRegion,
    estimatedDurationMinutes: 90,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 200,
    mealType: 'NONE' as MealType,
    tags: ['local', 'food', 'shopping', 'cultural', 'authentic', 'heritage'],
    rating: 4.2,
    reviewCount: 2400,
  },

  // ═══════════════════════════════════════
  // HERITAGE (2)
  // ═══════════════════════════════════════
  {
    name: 'Goa State Museum',
    description:
      'The official state museum of Goa, located in the EDC Complex at Patto in Panaji, housing an extensive collection spanning Goan history from the prehistoric era to the modern age. The museum features rare artifacts including Hindu and Jain sculptures, Portuguese-era furniture, coins, paintings, and an impressive collection of Goan Christian art. It is an essential stop for anyone wanting to understand Goa\'s rich multicultural heritage.',
    latitude: 15.4930,
    longitude: 73.8345,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'museum',
    region: 'CENTRAL' as GoaRegion,
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:30',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW' as BudgetTier,
    avgCostPerPerson: 20,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'museum', 'cultural', 'history', 'art', 'educational'],
    rating: 4.0,
    reviewCount: 1800,
  },
  {
    name: 'Fort Tiracol Heritage Hotel',
    description:
      'A beautifully restored heritage property within the walls of 17th-century Tiracol Fort, offering boutique accommodation at the northernmost point of Goa. The heritage hotel preserves the colonial-era charm with period furniture and whitewashed walls, while the fort\'s ramparts provide stunning views of the Arabian Sea and the Terekhol River estuary. Visitors can explore the fort\'s chapel and battlements even without a room reservation.',
    latitude: 15.7220,
    longitude: 73.6910,
    type: 'ATTRACTION' as PlaceType,
    categoryName: 'heritage',
    region: 'NORTH' as GoaRegion,
    estimatedDurationMinutes: 60,
    bestTimeStart: '09:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'HIGH' as BudgetTier,
    avgCostPerPerson: 500,
    mealType: 'NONE' as MealType,
    tags: ['heritage', 'luxury', 'boutique', 'scenic', 'historic', 'viewpoint', 'photography'],
    rating: 4.3,
    reviewCount: 1200,
  },
];
