import { PlaceType, BudgetTier, MealType, GoaRegion } from '@prisma/client';
import type { SeedPlace } from './places.js';

export const EXTRA_WATERFALLS: SeedPlace[] = [
  {
    name: 'Dudhsagar Waterfalls',
    description: "One of India's tallest waterfalls, located on the Mandovi River in the Bhagwan Mahaveer Sanctuary. The spectacular 'Sea of Milk' is a must-visit nature spot.",
    latitude: 15.3144,
    longitude: 74.3143,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 180,
    bestTimeStart: '09:00',
    bestTimeEnd: '15:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 500,
    mealType: 'NONE',
    tags: ['waterfall', 'nature', 'trekking', 'scenic'],
    rating: 4.8,
    reviewCount: 15200,
  },
  {
    name: 'Harvalem (Arvalem) Waterfalls',
    description: 'A beautiful and easily accessible waterfall located near the Arvalem caves and the Rudreshwar temple, dropping from a height of 50 meters.',
    latitude: 15.5668,
    longitude: 74.0249,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'NORTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'nature', 'peaceful'],
    rating: 4.2,
    reviewCount: 3100,
  },
  {
    name: 'Tambdi Surla Waterfalls',
    description: 'A pristine waterfall tucked deep inside the Bhagwan Mahavir Wildlife Sanctuary, requiring a scenic 90-minute trek from the ancient Tambdi Surla Mahadev Temple.',
    latitude: 15.4388,
    longitude: 74.2541,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '08:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'trekking', 'nature', 'wildlife'],
    rating: 4.5,
    reviewCount: 1200,
  },
  {
    name: 'Savari Waterfall (Netravali)',
    description: 'Located in the Netravali Wildlife Sanctuary, this majestic waterfall is reached via an adventurous trek crossing streams and lush green forests.',
    latitude: 15.0601,
    longitude: 74.2255,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '09:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 100,
    mealType: 'NONE',
    tags: ['waterfall', 'trekking', 'adventure', 'nature'],
    rating: 4.6,
    reviewCount: 950,
  },
  {
    name: 'Mainapi Waterfall (Netravali)',
    description: 'Another gem in the Netravali Wildlife Sanctuary, featuring a smaller but highly picturesque cascade with a refreshing pool at the base.',
    latitude: 15.0741,
    longitude: 74.2120,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '09:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 100,
    mealType: 'NONE',
    tags: ['waterfall', 'trekking', 'nature', 'hidden'],
    rating: 4.4,
    reviewCount: 680,
  },
  {
    name: 'Hivre Waterfalls',
    description: 'A hidden, multi-tiered waterfall in the Valpoi region that requires a thrilling trek through thick jungle and streams.',
    latitude: 15.5469,
    longitude: 74.1481,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'NORTH',
    estimatedDurationMinutes: 180,
    bestTimeStart: '08:00',
    bestTimeEnd: '15:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'trekking', 'nature', 'adventure'],
    rating: 4.7,
    reviewCount: 410,
  },
  {
    name: 'Bamanbudo Waterfalls',
    description: 'One of the most easily accessible waterfalls in South Goa, located right on the roadside against a scenic backdrop of greenery.',
    latitude: 15.0039,
    longitude: 74.1466,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'accessible', 'nature', 'scenic'],
    rating: 4.3,
    reviewCount: 890,
  },
  {
    name: 'Kuskem Waterfalls',
    description: 'A seasonal waterfall in the Canacona district, best visited during the monsoon, plunging from a lofty cliff in the Cotigao Wildlife Sanctuary.',
    latitude: 14.9912,
    longitude: 74.1350,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'monsoon', 'nature', 'trekking'],
    rating: 4.1,
    reviewCount: 520,
  },
  {
    name: 'Sada Waterfalls',
    description: 'Located in the Western Ghats on the Goa-Karnataka border, this magnificent waterfall offers a steep trek and breathtaking views.',
    latitude: 15.6565,
    longitude: 74.1561,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'NORTH',
    estimatedDurationMinutes: 240,
    bestTimeStart: '07:00',
    bestTimeEnd: '14:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'trekking', 'extreme', 'nature'],
    rating: 4.6,
    reviewCount: 230,
  },
  {
    name: 'Charavane Waterfall',
    description: 'A peaceful, cascading waterfall situated inside the Mhadei Wildlife Sanctuary, offering a scenic and relatively easy trek.',
    latitude: 15.5458,
    longitude: 74.1340,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '08:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['waterfall', 'trekking', 'nature', 'peaceful'],
    rating: 4.2,
    reviewCount: 300,
  }
];
