import { PlaceType, BudgetTier, MealType, GoaRegion } from '../generated/prisma/client.js';
import { nightlifeAndHeritageSeedData } from './scratch_nightlife_heritage.js';
import { SCRATCH_PLACES } from './scratch_attractions.js';
import { SCRATCH_RESTAURANTS } from './scratch_restaurants.js';
import { EXTRA_ATTRACTIONS } from './extra_attractions.js';
import { EXTRA_RESTAURANTS } from './extra_restaurants.js';
import { EXTRA_ACTIVITIES } from './extra_activities.js';

export interface SeedPlace {
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  type: PlaceType;
  categoryName: string; // matches CATEGORIES.name
  region: GoaRegion;
  estimatedDurationMinutes: number;
  bestTimeStart: string;
  bestTimeEnd: string;
  isOpenAtNight: boolean;
  budgetTier: BudgetTier;
  avgCostPerPerson: number | null;
  mealType: MealType;
  tags: string[];
  rating: number;
  reviewCount: number;
}

export const SEED_PLACES: SeedPlace[] = [
  // ═══════════════════════════════════════
  // NORTH GOA — BEACHES (8)
  // ═══════════════════════════════════════
  {
    name: 'Baga Beach',
    description: 'One of the most popular beaches in North Goa, known for its vibrant nightlife, water sports, and beach shacks.',
    latitude: 15.5553,
    longitude: 73.7514,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'family', 'nightlife', 'water-sports', 'popular'],
    rating: 4.3,
    reviewCount: 12500,
  },
  {
    name: 'Calangute Beach',
    description: 'The largest beach in North Goa, often called the Queen of Beaches. Bustling with tourists, shops, and restaurants.',
    latitude: 15.5438,
    longitude: 73.7553,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'family', 'popular', 'shopping'],
    rating: 4.1,
    reviewCount: 15800,
  },
  {
    name: 'Anjuna Beach',
    description: 'Famous for its rocky coastline, trance music scene, and the iconic Wednesday flea market.',
    latitude: 15.5725,
    longitude: 73.7404,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'adventure', 'nightlife', 'bohemian'],
    rating: 4.4,
    reviewCount: 9800,
  },
  {
    name: 'Vagator Beach',
    description: 'A stunning beach with red cliffs, dramatic rock formations, and views of Chapora Fort above.',
    latitude: 15.5955,
    longitude: 73.7327,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'romantic', 'photography', 'sunset'],
    rating: 4.5,
    reviewCount: 7200,
  },
  {
    name: 'Morjim Beach',
    description: 'A serene beach known as Turtle Beach due to Olive Ridley sea turtles that nest here.',
    latitude: 15.6308,
    longitude: 73.7275,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'peaceful', 'nature', 'wildlife'],
    rating: 4.3,
    reviewCount: 4100,
  },
  {
    name: 'Arambol Beach',
    description: 'A bohemian paradise with drum circles, yoga retreats, and a sweet water lagoon nearby.',
    latitude: 15.6866,
    longitude: 73.7036,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'bohemian', 'yoga', 'sunset', 'peaceful'],
    rating: 4.5,
    reviewCount: 6300,
  },
  {
    name: 'Mandrem Beach',
    description: 'A quiet, pristine beach perfect for relaxation. Less crowded than its neighbors.',
    latitude: 15.6636,
    longitude: 73.7103,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'peaceful', 'romantic', 'relaxation'],
    rating: 4.4,
    reviewCount: 3200,
  },
  {
    name: 'Sinquerim Beach',
    description: 'A calm beach near Fort Aguada, popular for dolphin-spotting boat rides and water sports.',
    latitude: 15.4958,
    longitude: 73.7658,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'NORTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'family', 'water-sports', 'dolphins'],
    rating: 4.2,
    reviewCount: 5100,
  },

  // ═══════════════════════════════════════
  // SOUTH GOA — BEACHES (6)
  // ═══════════════════════════════════════
  {
    name: 'Palolem Beach',
    description: 'A crescent-shaped paradise in South Goa with calm waters, kayaking, and silent noise parties.',
    latitude: 15.0100,
    longitude: 74.0239,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'SOUTH',
    estimatedDurationMinutes: 180,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'romantic', 'peaceful', 'kayaking', 'popular'],
    rating: 4.6,
    reviewCount: 11200,
  },
  {
    name: 'Agonda Beach',
    description: 'One of the most beautiful and unspoiled beaches in Goa. Voted among Asia\'s best beaches.',
    latitude: 15.0445,
    longitude: 74.0042,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'SOUTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'peaceful', 'romantic', 'nature', 'pristine'],
    rating: 4.7,
    reviewCount: 5800,
  },
  {
    name: 'Cola Beach',
    description: 'A hidden gem accessible by a steep trail, featuring a freshwater lagoon right next to the sea.',
    latitude: 15.0563,
    longitude: 74.0022,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'SOUTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'adventure', 'hidden-gem', 'lagoon', 'trekking'],
    rating: 4.5,
    reviewCount: 3400,
  },
  {
    name: 'Butterfly Beach',
    description: 'A secluded beach accessible only by boat from Palolem. Known for spotting butterflies and dolphins.',
    latitude: 15.0019,
    longitude: 74.0199,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'SOUTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '09:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 500,
    mealType: 'NONE',
    tags: ['scenic', 'adventure', 'hidden-gem', 'boat-ride', 'nature'],
    rating: 4.4,
    reviewCount: 2800,
  },
  {
    name: 'Benaulim Beach',
    description: 'A wide, clean beach in South Goa with fewer crowds. Great for long walks and fishing village vibes.',
    latitude: 15.2685,
    longitude: 73.9229,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'SOUTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'peaceful', 'family', 'fishing-village'],
    rating: 4.3,
    reviewCount: 4500,
  },
  {
    name: 'Colva Beach',
    description: 'One of the longest beaches in South Goa with white sand and a lively stretch of shacks.',
    latitude: 15.2801,
    longitude: 73.9117,
    type: 'ATTRACTION',
    categoryName: 'beach',
    region: 'SOUTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'family', 'popular', 'nightlife'],
    rating: 4.2,
    reviewCount: 7800,
  },

  // ═══════════════════════════════════════
  // FORTS (4)
  // ═══════════════════════════════════════
  {
    name: 'Fort Aguada',
    description: 'A well-preserved 17th-century Portuguese fort with a lighthouse offering panoramic sea views.',
    latitude: 15.4933,
    longitude: 73.7736,
    type: 'ATTRACTION',
    categoryName: 'fort',
    region: 'NORTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 50,
    mealType: 'NONE',
    tags: ['historic', 'scenic', 'photography', 'landmark', 'views'],
    rating: 4.4,
    reviewCount: 14200,
  },
  {
    name: 'Chapora Fort',
    description: 'Iconic fort made famous by the Bollywood film Dil Chahta Hai. Stunning sunset views over Vagator.',
    latitude: 15.6044,
    longitude: 73.7330,
    type: 'ATTRACTION',
    categoryName: 'fort',
    region: 'NORTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '15:00',
    bestTimeEnd: '18:30',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['historic', 'scenic', 'sunset', 'photography', 'bollywood', 'views'],
    rating: 4.5,
    reviewCount: 18500,
  },
  {
    name: 'Cabo de Rama Fort',
    description: 'An ancient fort on a cliff edge in South Goa with dramatic ocean views. Less touristy than northern forts.',
    latitude: 15.0870,
    longitude: 73.9270,
    type: 'ATTRACTION',
    categoryName: 'fort',
    region: 'SOUTH',
    estimatedDurationMinutes: 75,
    bestTimeStart: '09:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['historic', 'scenic', 'peaceful', 'off-beat', 'views'],
    rating: 4.3,
    reviewCount: 3100,
  },
  {
    name: 'Reis Magos Fort',
    description: 'A beautifully restored fort across the Mandovi river with art exhibitions and cultural events.',
    latitude: 15.5011,
    longitude: 73.8011,
    type: 'ATTRACTION',
    categoryName: 'fort',
    region: 'NORTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '09:30',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 50,
    mealType: 'NONE',
    tags: ['historic', 'art', 'cultural', 'restored', 'views'],
    rating: 4.2,
    reviewCount: 2400,
  },

  // ═══════════════════════════════════════
  // WATERFALLS (3)
  // ═══════════════════════════════════════
  {
    name: 'Dudhsagar Falls',
    description: 'One of India\'s tallest waterfalls (310m) deep in the Western Ghats. Accessible by jeep safari through the jungle.',
    latitude: 15.3144,
    longitude: 74.3143,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'SOUTH',
    estimatedDurationMinutes: 240,
    bestTimeStart: '07:00',
    bestTimeEnd: '15:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 800,
    mealType: 'NONE',
    tags: ['scenic', 'adventure', 'nature', 'trekking', 'must-visit', 'photography'],
    rating: 4.7,
    reviewCount: 22000,
  },
  {
    name: 'Tambdi Surla Waterfall',
    description: 'A hidden waterfall in Mollem National Park, reachable via a scenic forest trek.',
    latitude: 15.4558,
    longitude: 74.2442,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'CENTRAL',
    estimatedDurationMinutes: 120,
    bestTimeStart: '08:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 100,
    mealType: 'NONE',
    tags: ['scenic', 'adventure', 'nature', 'trekking', 'off-beat'],
    rating: 4.3,
    reviewCount: 1800,
  },
  {
    name: 'Savoi Waterfalls',
    description: 'A lesser-known waterfall surrounded by spice plantations. Best visited during monsoon season.',
    latitude: 15.5233,
    longitude: 73.9844,
    type: 'ATTRACTION',
    categoryName: 'waterfall',
    region: 'NORTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 50,
    mealType: 'NONE',
    tags: ['scenic', 'nature', 'off-beat', 'monsoon'],
    rating: 4.0,
    reviewCount: 1200,
  },

  // ═══════════════════════════════════════
  // TEMPLES & CHURCHES (4)
  // ═══════════════════════════════════════
  {
    name: 'Basilica of Bom Jesus',
    description: 'A UNESCO World Heritage Site housing the remains of St. Francis Xavier. A masterpiece of Baroque architecture.',
    latitude: 15.5009,
    longitude: 73.9116,
    type: 'ATTRACTION',
    categoryName: 'church',
    region: 'CENTRAL',
    estimatedDurationMinutes: 60,
    bestTimeStart: '09:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['historic', 'heritage', 'UNESCO', 'architecture', 'religious'],
    rating: 4.6,
    reviewCount: 16700,
  },
  {
    name: 'Se Cathedral',
    description: 'One of the largest churches in Asia, known for its massive golden bell and Portuguese-Manueline architecture.',
    latitude: 15.5038,
    longitude: 73.9128,
    type: 'ATTRACTION',
    categoryName: 'church',
    region: 'CENTRAL',
    estimatedDurationMinutes: 45,
    bestTimeStart: '09:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['historic', 'heritage', 'architecture', 'religious'],
    rating: 4.5,
    reviewCount: 8900,
  },
  {
    name: 'Shantadurga Temple',
    description: 'One of the most famous Hindu temples in Goa, dedicated to Goddess Shantadurga with beautiful Maratha-Portuguese architecture.',
    latitude: 15.4447,
    longitude: 73.9661,
    type: 'ATTRACTION',
    categoryName: 'temple',
    region: 'CENTRAL',
    estimatedDurationMinutes: 45,
    bestTimeStart: '06:00',
    bestTimeEnd: '20:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['religious', 'cultural', 'architecture', 'peaceful'],
    rating: 4.5,
    reviewCount: 5600,
  },
  {
    name: 'Mangeshi Temple',
    description: 'An important Shiva temple with a distinctive seven-storey deepastambha (lamp tower) and ornate interiors.',
    latitude: 15.4553,
    longitude: 73.9614,
    type: 'ATTRACTION',
    categoryName: 'temple',
    region: 'CENTRAL',
    estimatedDurationMinutes: 40,
    bestTimeStart: '06:00',
    bestTimeEnd: '21:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['religious', 'cultural', 'architecture', 'peaceful'],
    rating: 4.4,
    reviewCount: 4200,
  },

  // ═══════════════════════════════════════
  // MARKETS (3)
  // ═══════════════════════════════════════
  {
    name: 'Arpora Saturday Night Market',
    description: 'A vibrant night bazaar with live music, international food stalls, handicrafts, and a party atmosphere.',
    latitude: 15.5665,
    longitude: 73.7698,
    type: 'ATTRACTION',
    categoryName: 'market',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '18:00',
    bestTimeEnd: '23:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 500,
    mealType: 'NONE',
    tags: ['shopping', 'nightlife', 'food', 'music', 'cultural'],
    rating: 4.3,
    reviewCount: 6700,
  },
  {
    name: 'Anjuna Flea Market',
    description: 'A legendary Wednesday market selling everything from hippie clothing to spices and souvenirs.',
    latitude: 15.5716,
    longitude: 73.7405,
    type: 'ATTRACTION',
    categoryName: 'market',
    region: 'NORTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '09:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 300,
    mealType: 'NONE',
    tags: ['shopping', 'cultural', 'hippie', 'souvenirs'],
    rating: 4.1,
    reviewCount: 8900,
  },
  {
    name: 'Mapusa Friday Market',
    description: 'An authentic local market selling fresh produce, Goan sausages, feni, spices, and traditional items.',
    latitude: 15.5914,
    longitude: 73.8072,
    type: 'ATTRACTION',
    categoryName: 'market',
    region: 'NORTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '08:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 200,
    mealType: 'NONE',
    tags: ['shopping', 'local', 'authentic', 'food', 'spices'],
    rating: 4.2,
    reviewCount: 3500,
  },

  // ═══════════════════════════════════════
  // NATURE & TREKS (4)
  // ═══════════════════════════════════════
  {
    name: 'Mollem National Park',
    description: 'A biodiversity hotspot in the Western Ghats with jungle treks, Devil\'s Canyon, and rich birdlife.',
    latitude: 15.3644,
    longitude: 74.2433,
    type: 'ACTIVITY',
    categoryName: 'nature',
    region: 'CENTRAL',
    estimatedDurationMinutes: 180,
    bestTimeStart: '07:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 200,
    mealType: 'NONE',
    tags: ['nature', 'trekking', 'adventure', 'wildlife', 'birdwatching'],
    rating: 4.4,
    reviewCount: 3800,
  },
  {
    name: 'Netravali Wildlife Sanctuary',
    description: 'Home to the mysterious Bubbling Lake and pristine forest trails. Great for serious nature lovers.',
    latitude: 15.1358,
    longitude: 74.1694,
    type: 'ACTIVITY',
    categoryName: 'nature',
    region: 'SOUTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '07:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 100,
    mealType: 'NONE',
    tags: ['nature', 'trekking', 'off-beat', 'wildlife', 'peaceful'],
    rating: 4.2,
    reviewCount: 1500,
  },
  {
    name: 'Cotigao Wildlife Sanctuary',
    description: 'South Goa\'s largest wildlife sanctuary with tall trees, a tree-top watchtower, and rare birds.',
    latitude: 14.9800,
    longitude: 74.1000,
    type: 'ACTIVITY',
    categoryName: 'nature',
    region: 'SOUTH',
    estimatedDurationMinutes: 150,
    bestTimeStart: '07:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 100,
    mealType: 'NONE',
    tags: ['nature', 'trekking', 'wildlife', 'birdwatching', 'off-beat'],
    rating: 4.1,
    reviewCount: 1200,
  },
  {
    name: 'Sahakari Spice Farm',
    description: 'A guided tour through a working spice plantation with tastings, traditional Goan lunch, and elephant interaction.',
    latitude: 15.4400,
    longitude: 73.9900,
    type: 'ACTIVITY',
    categoryName: 'nature',
    region: 'CENTRAL',
    estimatedDurationMinutes: 120,
    bestTimeStart: '09:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 500,
    mealType: 'NONE',
    tags: ['nature', 'family', 'cultural', 'food', 'educational'],
    rating: 4.3,
    reviewCount: 4800,
  },

  // ═══════════════════════════════════════
  // VIEWPOINTS (2)
  // ═══════════════════════════════════════
  {
    name: 'Divar Island',
    description: 'A tranquil island on the Mandovi river accessible by ferry. Portuguese-era churches, paddy fields, and panoramic views.',
    latitude: 15.5200,
    longitude: 73.8814,
    type: 'ATTRACTION',
    categoryName: 'viewpoint',
    region: 'CENTRAL',
    estimatedDurationMinutes: 120,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 50,
    mealType: 'NONE',
    tags: ['scenic', 'peaceful', 'off-beat', 'photography', 'heritage'],
    rating: 4.3,
    reviewCount: 2100,
  },
  {
    name: 'Chapel of Our Lady of the Mount',
    description: 'A hilltop chapel in Old Goa offering breathtaking panoramic views of the Mandovi river and surrounding countryside.',
    latitude: 15.4155,
    longitude: 73.8678,
    type: 'ATTRACTION',
    categoryName: 'viewpoint',
    region: 'CENTRAL',
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:00',
    bestTimeEnd: '17:30',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 0,
    mealType: 'NONE',
    tags: ['scenic', 'peaceful', 'views', 'heritage', 'photography'],
    rating: 4.4,
    reviewCount: 1800,
  },

  // ═══════════════════════════════════════
  // ACTIVITIES / WATER SPORTS (4)
  // ═══════════════════════════════════════
  {
    name: 'Grande Island Boat Trip',
    description: 'A full-day boat trip with snorkeling, scuba diving, fishing, and lunch on a secluded island.',
    latitude: 15.3800,
    longitude: 73.7800,
    type: 'ACTIVITY',
    categoryName: 'water-sports',
    region: 'CENTRAL',
    estimatedDurationMinutes: 300,
    bestTimeStart: '08:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'HIGH',
    avgCostPerPerson: 2500,
    mealType: 'NONE',
    tags: ['adventure', 'water-sports', 'snorkeling', 'scuba', 'boat-ride'],
    rating: 4.5,
    reviewCount: 5200,
  },
  {
    name: 'Sinquerim Dolphin Trip',
    description: 'An early morning boat ride to spot Indo-Pacific humpback dolphins in the Arabian Sea.',
    latitude: 15.4950,
    longitude: 73.7690,
    type: 'ACTIVITY',
    categoryName: 'water-sports',
    region: 'NORTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '07:00',
    bestTimeEnd: '10:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 600,
    mealType: 'NONE',
    tags: ['adventure', 'nature', 'dolphins', 'boat-ride', 'family'],
    rating: 4.2,
    reviewCount: 3200,
  },
  {
    name: 'Palolem Kayaking',
    description: 'Kayak through calm waters along Palolem\'s coast, exploring hidden coves and Butterfly Beach.',
    latitude: 15.0105,
    longitude: 74.0230,
    type: 'ACTIVITY',
    categoryName: 'water-sports',
    region: 'SOUTH',
    estimatedDurationMinutes: 120,
    bestTimeStart: '07:00',
    bestTimeEnd: '16:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 800,
    mealType: 'NONE',
    tags: ['adventure', 'water-sports', 'kayaking', 'scenic', 'nature'],
    rating: 4.4,
    reviewCount: 2800,
  },
  {
    name: 'Calangute Water Sports',
    description: 'Jet skiing, parasailing, banana boat rides, and bumper rides at Calangute\'s main water sports zone.',
    latitude: 15.5430,
    longitude: 73.7555,
    type: 'ACTIVITY',
    categoryName: 'water-sports',
    region: 'NORTH',
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:00',
    bestTimeEnd: '17:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 1000,
    mealType: 'NONE',
    tags: ['adventure', 'water-sports', 'family', 'thrill'],
    rating: 4.0,
    reviewCount: 6100,
  },

  // ═══════════════════════════════════════
  // RESTAURANTS — NORTH GOA (6)
  // ═══════════════════════════════════════
  {
    name: 'Thalassa',
    description: 'Iconic Greek restaurant perched on Vagator cliffs. Famous for sunset views and Mediterranean cuisine.',
    latitude: 15.5925,
    longitude: 73.7350,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'NORTH',
    estimatedDurationMinutes: 75,
    bestTimeStart: '12:00',
    bestTimeEnd: '23:00',
    isOpenAtNight: true,
    budgetTier: 'HIGH',
    avgCostPerPerson: 1500,
    mealType: 'DINNER',
    tags: ['non-veg', 'veg', 'scenic', 'romantic', 'sunset', 'greek'],
    rating: 4.5,
    reviewCount: 9800,
  },
  {
    name: 'Curlies Beach Shack',
    description: 'Legendary Anjuna beach shack known for its chilled vibes, seafood, and trance music nights.',
    latitude: 15.5700,
    longitude: 73.7380,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'NORTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '09:00',
    bestTimeEnd: '02:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 600,
    mealType: 'LUNCH',
    tags: ['non-veg', 'veg', 'seafood', 'beach', 'nightlife'],
    rating: 4.2,
    reviewCount: 7200,
  },
  {
    name: 'Gunpowder',
    description: 'Charming garden restaurant in Assagao serving authentic South Indian and Goan cuisine.',
    latitude: 15.5800,
    longitude: 73.7600,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'NORTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '12:30',
    bestTimeEnd: '22:30',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 700,
    mealType: 'LUNCH',
    tags: ['non-veg', 'veg', 'south-indian', 'goan', 'garden'],
    rating: 4.5,
    reviewCount: 5400,
  },
  {
    name: "Britto's",
    description: 'A Baga Beach institution since 1965. Open-air seafood dining right on the sand.',
    latitude: 15.5519,
    longitude: 73.7545,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'NORTH',
    estimatedDurationMinutes: 75,
    bestTimeStart: '08:00',
    bestTimeEnd: '23:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 800,
    mealType: 'LUNCH',
    tags: ['non-veg', 'veg', 'seafood', 'beach', 'family', 'iconic'],
    rating: 4.3,
    reviewCount: 12100,
  },
  {
    name: 'Artjuna Garden Cafe',
    description: 'A bohemian breakfast spot in Anjuna with organic food, fresh juices, and a relaxed garden setting.',
    latitude: 15.5772,
    longitude: 73.7441,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'NORTH',
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 400,
    mealType: 'BREAKFAST',
    tags: ['veg', 'vegan', 'organic', 'healthy', 'bohemian', 'garden'],
    rating: 4.4,
    reviewCount: 3100,
  },
  {
    name: 'Infantaria',
    description: 'Famous Calangute bakery and cafe known for its croissants, breakfast platters, and Goan pastries.',
    latitude: 15.5375,
    longitude: 73.7600,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'NORTH',
    estimatedDurationMinutes: 45,
    bestTimeStart: '07:30',
    bestTimeEnd: '22:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 350,
    mealType: 'BREAKFAST',
    tags: ['veg', 'non-veg', 'bakery', 'breakfast', 'pastries'],
    rating: 4.3,
    reviewCount: 6800,
  },

  // ═══════════════════════════════════════
  // RESTAURANTS — CENTRAL GOA (3)
  // ═══════════════════════════════════════
  {
    name: 'Ritz Classic',
    description: 'A Panjim institution serving legendary Goan fish thali. No-frills, authentic, and packed at lunch.',
    latitude: 15.4969,
    longitude: 73.8128,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'CENTRAL',
    estimatedDurationMinutes: 45,
    bestTimeStart: '11:30',
    bestTimeEnd: '15:00',
    isOpenAtNight: false,
    budgetTier: 'LOW',
    avgCostPerPerson: 250,
    mealType: 'LUNCH',
    tags: ['non-veg', 'goan', 'authentic', 'local', 'fish-thali'],
    rating: 4.4,
    reviewCount: 4500,
  },
  {
    name: "Mum's Kitchen",
    description: 'Award-winning restaurant preserving traditional Goan recipes passed down through generations.',
    latitude: 15.4902,
    longitude: 73.8243,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'CENTRAL',
    estimatedDurationMinutes: 60,
    bestTimeStart: '12:00',
    bestTimeEnd: '22:30',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 600,
    mealType: 'DINNER',
    tags: ['non-veg', 'veg', 'goan', 'traditional', 'award-winning'],
    rating: 4.5,
    reviewCount: 5200,
  },
  {
    name: 'Cafe Bodega',
    description: 'A stylish cafe in a restored art gallery in Panjim. Excellent coffee, European pastries, and light meals.',
    latitude: 15.5009,
    longitude: 73.8167,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'CENTRAL',
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:30',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 350,
    mealType: 'BREAKFAST',
    tags: ['veg', 'non-veg', 'cafe', 'breakfast', 'european', 'art'],
    rating: 4.5,
    reviewCount: 3800,
  },

  // ═══════════════════════════════════════
  // RESTAURANTS — SOUTH GOA (4)
  // ═══════════════════════════════════════
  {
    name: "Martin's Corner",
    description: 'A South Goa legend serving fiery Goan cuisine with live music. Try the prawn balchão and pork vindaloo.',
    latitude: 15.2958,
    longitude: 73.9036,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'SOUTH',
    estimatedDurationMinutes: 75,
    bestTimeStart: '12:00',
    bestTimeEnd: '23:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 700,
    mealType: 'DINNER',
    tags: ['non-veg', 'goan', 'seafood', 'live-music', 'iconic'],
    rating: 4.4,
    reviewCount: 8900,
  },
  {
    name: 'Zeebop by the Sea',
    description: 'A beach shack in Utorda serving some of the best seafood in South Goa with tables right on the sand.',
    latitude: 15.2555,
    longitude: 73.9272,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'SOUTH',
    estimatedDurationMinutes: 75,
    bestTimeStart: '12:00',
    bestTimeEnd: '22:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 800,
    mealType: 'LUNCH',
    tags: ['non-veg', 'seafood', 'beach', 'scenic', 'family'],
    rating: 4.5,
    reviewCount: 4200,
  },
  {
    name: 'Dropadi',
    description: 'A cozy multi-cuisine restaurant in Palolem known for its fresh seafood platters and friendly service.',
    latitude: 15.0105,
    longitude: 74.0230,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'SOUTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '11:00',
    bestTimeEnd: '22:30',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 400,
    mealType: 'LUNCH',
    tags: ['non-veg', 'veg', 'seafood', 'multi-cuisine', 'family'],
    rating: 4.3,
    reviewCount: 2800,
  },
  {
    name: 'Magic Italy',
    description: 'Authentic Italian restaurant in Palolem run by Italian expats. Wood-fired pizzas and homemade pasta.',
    latitude: 15.0098,
    longitude: 74.0235,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'SOUTH',
    estimatedDurationMinutes: 60,
    bestTimeStart: '18:00',
    bestTimeEnd: '22:30',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 600,
    mealType: 'DINNER',
    tags: ['veg', 'non-veg', 'italian', 'pizza', 'pasta'],
    rating: 4.4,
    reviewCount: 2200,
  },

  // ═══════════════════════════════════════
  // RESTAURANTS — Extra for meal variety (2)
  // ═══════════════════════════════════════
  {
    name: "Fisherman's Wharf",
    description: 'Popular riverside restaurant chain with multiple locations. Known for Goan fish curry rice and prawn dishes.',
    latitude: 15.1794,
    longitude: 73.9417,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'SOUTH',
    estimatedDurationMinutes: 75,
    bestTimeStart: '12:00',
    bestTimeEnd: '23:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM',
    avgCostPerPerson: 700,
    mealType: 'DINNER',
    tags: ['non-veg', 'veg', 'goan', 'seafood', 'family', 'riverside'],
    rating: 4.3,
    reviewCount: 7800,
  },
  {
    name: 'Vinayak Family Restaurant',
    description: 'A beloved pure-veg restaurant in Panjim serving Goan vegetarian and North Indian dishes at pocket-friendly prices.',
    latitude: 15.4979,
    longitude: 73.8126,
    type: 'RESTAURANT',
    categoryName: 'restaurant',
    region: 'CENTRAL',
    estimatedDurationMinutes: 45,
    bestTimeStart: '08:00',
    bestTimeEnd: '22:00',
    isOpenAtNight: true,
    budgetTier: 'LOW',
    avgCostPerPerson: 200,
    mealType: 'LUNCH',
    tags: ['veg', 'indian', 'local', 'family', 'budget-friendly'],
    rating: 4.2,
    reviewCount: 3600,
  },
  ...nightlifeAndHeritageSeedData,
  ...SCRATCH_PLACES,
  ...SCRATCH_RESTAURANTS,
  ...EXTRA_ATTRACTIONS,
  ...EXTRA_RESTAURANTS,
  ...EXTRA_ACTIVITIES,
];
