/**
 * Seed data: Goa Nightlife & Heritage
 *
 * Sources: Google Maps, TripAdvisor, MakeMyTrip, Justdial, official venue sites.
 * Coordinates verified to be within Goa range (lat ~14.5-15.9, lng ~73.5-74.5).
 * Last researched: June 2026
 */

export const nightlifeAndHeritageSeedData = [
  // ═══════════════════════════════════════════
  //  NIGHTLIFE VENUES (8)
  // ═══════════════════════════════════════════

  {
    name: 'Club Cubana',
    description:
      'Known as the "Nightclub in the Sky," this legendary hilltop venue on Arpora Hill features a multi-level layout with a swimming pool, jacuzzi, and neon-lit dance floors overlooking North Goa.',
    latitude: 15.5757,
    longitude: 73.7667,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 180,
    bestTimeStart: '21:00',
    bestTimeEnd: '03:00',
    isOpenAtNight: true,
    budgetTier: 'HIGH' as const,
    avgCostPerPerson: 1500,
    mealType: 'NONE' as const,
    tags: ['nightclub', 'hilltop', 'pool-party', 'dancing', 'dj', 'neon', 'couples'],
    rating: 3.9,
    reviewCount: 2600,
  },

  {
    name: 'LPK Waterfront',
    description:
      'Love Passion Karma (LPK) is a riverside nightclub in Nerul featuring stunning hand-carved terracotta statues, cave-themed interiors, and an open-air dance floor set against a 400-year-old Indo-Portuguese church.',
    latitude: 15.5085,
    longitude: 73.7745,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 180,
    bestTimeStart: '21:30',
    bestTimeEnd: '03:30',
    isOpenAtNight: true,
    budgetTier: 'HIGH' as const,
    avgCostPerPerson: 1500,
    mealType: 'NONE' as const,
    tags: ['nightclub', 'riverside', 'terracotta', 'edm', 'bollywood', 'trance', 'open-air'],
    rating: 3.9,
    reviewCount: 1800,
  },

  {
    name: 'Cafe Mambo',
    description:
      'Located on the iconic Tito\'s Lane in Baga, Cafe Mambo is one of Goa\'s most popular nightlife destinations with an energetic dance floor, top DJs, and a mix of indoor and open-air lounge seating.',
    latitude: 15.5561,
    longitude: 73.7522,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 210,
    bestTimeStart: '21:00',
    bestTimeEnd: '04:00',
    isOpenAtNight: true,
    budgetTier: 'HIGH' as const,
    avgCostPerPerson: 1500,
    mealType: 'NONE' as const,
    tags: ['nightclub', 'titos-lane', 'dancing', 'dj', 'baga', 'party', 'bar'],
    rating: 4.5,
    reviewCount: 8000,
  },

  {
    name: 'Chronicle',
    description:
      'A multi-level cliffside beach club and lounge bar at Little Vagator, Chronicle offers Italian fine dining, an elite cocktail bar, and an open-air dance floor carved into the rocks with stunning sea views.',
    latitude: 15.5977,
    longitude: 73.7450,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 180,
    bestTimeStart: '18:00',
    bestTimeEnd: '02:00',
    isOpenAtNight: true,
    budgetTier: 'HIGH' as const,
    avgCostPerPerson: 2000,
    mealType: 'DINNER' as const,
    tags: ['lounge-bar', 'cliffside', 'beach-club', 'cocktails', 'fine-dining', 'dj', 'sunset'],
    rating: 4.1,
    reviewCount: 1200,
  },

  {
    name: 'Cape Town Cafe',
    description:
      'A high-energy party venue on Tito\'s Lane in Baga, Cape Town Cafe doubles as a sports bar, restaurant, and nightclub with a massive dance floor, state-of-the-art sound system, and themed event nights.',
    latitude: 15.5570,
    longitude: 73.7548,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 180,
    bestTimeStart: '21:00',
    bestTimeEnd: '03:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM' as const,
    avgCostPerPerson: 1200,
    mealType: 'NONE' as const,
    tags: ['nightclub', 'sports-bar', 'titos-lane', 'dancing', 'dj', 'party', 'baga'],
    rating: 3.9,
    reviewCount: 2200,
  },

  {
    name: 'SinQ Night Club',
    description:
      'An upscale four-zone nightlife complex in Sinquerim featuring an industrial-chic nightclub, a contemporary Goan tavern, a poolside deck, and a lounge — all opposite the Taj Holiday Village on Fort Aguada Road.',
    latitude: 15.5126,
    longitude: 73.7663,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 180,
    bestTimeStart: '21:00',
    bestTimeEnd: '03:00',
    isOpenAtNight: true,
    budgetTier: 'HIGH' as const,
    avgCostPerPerson: 2000,
    mealType: 'NONE' as const,
    tags: ['nightclub', 'upscale', 'poolside', 'lounge', 'edm', 'bollywood', 'couples'],
    rating: 4.1,
    reviewCount: 3500,
  },

  {
    name: 'Hilltop',
    description:
      'A legendary open-air psytrance venue in a neon-lit palm grove on Ozran Beach Road, Vagator. Hilltop is a global pilgrimage site for psychedelic trance culture, famous for its Sunday sessions and international DJ lineups.',
    latitude: 15.5925,
    longitude: 73.7424,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 240,
    bestTimeStart: '17:00',
    bestTimeEnd: '22:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM' as const,
    avgCostPerPerson: 1000,
    mealType: 'NONE' as const,
    tags: ['psytrance', 'open-air', 'palm-grove', 'dj', 'electronic', 'vagator', 'legendary'],
    rating: 4.3,
    reviewCount: 1500,
  },

  {
    name: 'Leopard Valley',
    description:
      'South Goa\'s premier open-air nightclub carved into a jungle quarry between Palolem and Agonda, featuring a 7-meter-high DJ booth, laser shows, fire performances, and epic Friday night parties under the stars.',
    latitude: 15.0210,
    longitude: 74.0325,
    type: 'ACTIVITY' as const,
    categoryName: 'nightlife',
    region: 'SOUTH' as const,
    estimatedDurationMinutes: 240,
    bestTimeStart: '21:00',
    bestTimeEnd: '04:00',
    isOpenAtNight: true,
    budgetTier: 'MEDIUM' as const,
    avgCostPerPerson: 1000,
    mealType: 'NONE' as const,
    tags: ['nightclub', 'jungle', 'open-air', 'laser-show', 'palolem', 'friday-nights', 'south-goa'],
    rating: 4.2,
    reviewCount: 900,
  },

  // ═══════════════════════════════════════════
  //  HERITAGE SITES (5)
  // ═══════════════════════════════════════════

  {
    name: 'Fontainhas Latin Quarter',
    description:
      'India\'s only Latin Quarter, Fontainhas is a UNESCO-listed heritage zone in Panjim featuring narrow cobblestone lanes lined with colorful Portuguese-era villas, century-old bakeries, art galleries, and the Chapel of St. Sebastian.',
    latitude: 15.4961,
    longitude: 73.8311,
    type: 'ATTRACTION' as const,
    categoryName: 'heritage',
    region: 'CENTRAL' as const,
    estimatedDurationMinutes: 150,
    bestTimeStart: '08:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as const,
    avgCostPerPerson: null,
    mealType: 'NONE' as const,
    tags: ['portuguese', 'heritage-walk', 'colonial', 'architecture', 'photography', 'panjim', 'latin-quarter'],
    rating: 4.5,
    reviewCount: 4500,
  },

  {
    name: 'Museum of Goa (MOG)',
    description:
      'Founded by artist Dr. Subodh Kerkar in 2015, MOG is Goa\'s premier contemporary art museum in Pilerne featuring rotating exhibitions, installations, a sculpture garden, and the popular weekly "MOG Sundays" lecture series.',
    latitude: 15.5255,
    longitude: 73.7953,
    type: 'ATTRACTION' as const,
    categoryName: 'heritage',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 90,
    bestTimeStart: '10:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as const,
    avgCostPerPerson: 300,
    mealType: 'NONE' as const,
    tags: ['museum', 'contemporary-art', 'gallery', 'installations', 'sculpture-garden', 'cultural'],
    rating: 4.4,
    reviewCount: 800,
  },

  {
    name: 'Church of St. Francis of Assisi',
    description:
      'A UNESCO World Heritage Site in Old Goa dating back to the Portuguese era, this church features a stunning Manueline doorway, Baroque interior, and an adjoining convent now housing the Archaeological Museum of Goa.',
    latitude: 15.5032,
    longitude: 73.9113,
    type: 'ATTRACTION' as const,
    categoryName: 'heritage',
    region: 'CENTRAL' as const,
    estimatedDurationMinutes: 45,
    bestTimeStart: '07:30',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as const,
    avgCostPerPerson: null,
    mealType: 'NONE' as const,
    tags: ['unesco', 'church', 'portuguese', 'baroque', 'heritage', 'old-goa', 'museum'],
    rating: 4.4,
    reviewCount: 3200,
  },

  {
    name: 'Ancestral Goa Museum (Big Foot)',
    description:
      'An immersive open-air museum in Loutolim depicting rural Goan life from over a century ago with life-sized laterite sculptures, traditional architecture, a 14-meter Sant Mirabai statue, and a heritage mansion tour.',
    latitude: 15.3396,
    longitude: 73.9875,
    type: 'ATTRACTION' as const,
    categoryName: 'heritage',
    region: 'SOUTH' as const,
    estimatedDurationMinutes: 90,
    bestTimeStart: '09:00',
    bestTimeEnd: '18:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as const,
    avgCostPerPerson: 150,
    mealType: 'NONE' as const,
    tags: ['museum', 'open-air', 'cultural', 'sculpture', 'traditional', 'rural-life', 'loutolim'],
    rating: 4.1,
    reviewCount: 8000,
  },

  {
    name: 'Houses of Goa Museum',
    description:
      'Designed by architect Gerard da Cunha in a distinctive ship-shaped laterite building, this Torda museum chronicles the evolution of Goan residential architecture through models, photographs, and exhibits of Indo-Portuguese design.',
    latitude: 15.5303,
    longitude: 73.8407,
    type: 'ATTRACTION' as const,
    categoryName: 'heritage',
    region: 'NORTH' as const,
    estimatedDurationMinutes: 60,
    bestTimeStart: '10:00',
    bestTimeEnd: '19:00',
    isOpenAtNight: false,
    budgetTier: 'LOW' as const,
    avgCostPerPerson: 150,
    mealType: 'NONE' as const,
    tags: ['museum', 'architecture', 'portuguese', 'laterite', 'heritage', 'torda', 'design'],
    rating: 4.2,
    reviewCount: 3230,
  },
];
